services:
  - type: web
    name: power-outage-bot
    runtime: python
    region: frankfurt
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: python Bot.py

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true

    aptPackages:
      - chromium
      - chromium-driver